[Icon Theme]
Name=Forge Core
Comment=Forge Core - metropole futurista autossuficiente. Sci-fi industrial, superfícies grafite, iluminacao #fc435a.
Inherits=Yaru,Humanity,Adwaita,hicolor
Example=folder
Directories=16x16/actions,16x16/apps,16x16/places,22x22/actions,22x22/apps,22x22/places,24x24/actions,24x24/apps,24x24/places,32x32/actions,32x32/apps,32x32/places,48x48/actions,48x48/apps,48x48/places,64x64/actions,64x64/apps,64x64/places,96x96/actions,96x96/apps,96x96/places,128x128/actions,128x128/apps,128x128/places,256x256/actions,256x256/apps,256x256/places,scalable/actions,scalable/apps,scalable/devices,scalable/status

[scalable/actions]
Size=16
Context=Actions
Type=Scalable
MinSize=8
MaxSize=512

[scalable/apps]
Size=16
Context=Apps
Type=Scalable
MinSize=8
MaxSize=512

[scalable/devices]
Size=16
Context=Devices
Type=Scalable
MinSize=8
MaxSize=512

[scalable/status]
Size=16
Context=Status
Type=Scalable
MinSize=8
MaxSize=512

[16x16/actions]
Size=16
Context=Actions
Type=Fixed

[16x16/apps]
Size=16
Context=Apps
Type=Fixed

[16x16/places]
Size=16
Context=Places
Type=Fixed

[22x22/actions]
Size=22
Context=Actions
Type=Fixed

[22x22/apps]
Size=22
Context=Apps
Type=Fixed

[22x22/places]
Size=22
Context=Places
Type=Fixed

[24x24/actions]
Size=24
Context=Actions
Type=Fixed

[24x24/apps]
Size=24
Context=Apps
Type=Fixed

[24x24/places]
Size=24
Context=Places
Type=Fixed

[32x32/actions]
Size=32
Context=Actions
Type=Fixed

[32x32/apps]
Size=32
Context=Apps
Type=Fixed

[32x32/places]
Size=32
Context=Places
Type=Fixed

[48x48/actions]
Size=48
Context=Actions
Type=Fixed

[48x48/apps]
Size=48
Context=Apps
Type=Fixed

[48x48/places]
Size=48
Context=Places
Type=Fixed

[64x64/actions]
Size=64
Context=Actions
Type=Fixed

[64x64/apps]
Size=64
Context=Apps
Type=Fixed

[64x64/places]
Size=64
Context=Places
Type=Fixed

[96x96/actions]
Size=96
Context=Actions
Type=Fixed

[96x96/apps]
Size=96
Context=Apps
Type=Fixed

[96x96/places]
Size=96
Context=Places
Type=Fixed

[128x128/actions]
Size=128
Context=Actions
Type=Fixed

[128x128/apps]
Size=128
Context=Apps
Type=Fixed

[128x128/places]
Size=128
Context=Places
Type=Fixed

[256x256/actions]
Size=256
Context=Actions
Type=Scalable
MinSize=192
MaxSize=512

[256x256/apps]
Size=256
Context=Apps
Type=Scalable
MinSize=192
MaxSize=512

[256x256/places]
Size=256
Context=Places
Type=Scalable
MinSize=192
MaxSize=512
